// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class OsterhaseDbdb : DataConnection
	{
		public OsterhaseDbdb()
		{
			InitDataContext();
		}

		public OsterhaseDbdb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public OsterhaseDbdb(DataOptions<OsterhaseDbdb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Personen> Personens => this.GetTable<Personen>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Personen? Find(this ITable<Personen> table, long id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Personen?> FindAsync(this ITable<Personen> table, long id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}
