// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Personen")]
	public class Personen
	{
		[Column("ID"       , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    Id        { get; set; } // integer
		[Column("Name"     , CanBeNull    = false                                                             )] public string  Name      { get; set; } = null!; // text(max)
		[Column("Longitude"                                                                                   )] public decimal Longitude { get; set; } // numeric
		[Column("Latitude"                                                                                    )] public decimal Latitude  { get; set; } // numeric


        public override string ToString()
        {
            return $"{Name}, {Longitude}, {Latitude}";
        }
    }
}
